name: Generate pacman animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: JEETJM

      - name: Deploy pacman graph to output-pacman branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output-pacman
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
